version: "3.9"
services:
  test-runner:
    build: .
    volumes:
      - .:/app
    environment:
      - CHROME_BIN=/usr/bin/chromium
      - CHROME_DRIVER=/usr/bin/chromedriver
    command: pytest tests/test_login.py
    # Ensure we have enough time to start the browser
    entrypoint: ["pytest", "tests/test_login.py"]
